### ISSUE TITLE
Maybe in README.md suggest installation of hhvm-dev as an alternative option to using source?

### ISSUE THREAD

**Issue by mzaslavsky** [vipsoft/hhvm-ext-geoip#18]
As mentioned in https://github.com/vipsoft/hhvm-ext-geoip/issues/12, it's possible to install hhvm-dev to access hphpize rather than slowly compile hhvm from source. The user will still need to install all dependencies as necessary (e.g. third-party libraries in Ubuntu 12.04 - https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-12.04) but the overall process would be much quicker.

**Comment by steelbrain** [comment]
I always install hhvm-dev instead of compiling hhvm from source. Works cool for me.
